In [15]:
import pandas as pd
import json 
from bs4 import BeautifulSoup

In [16]:
"Data Directory"
js= 'user_data.json'
xml='user_data.xml'
csv='user_data.csv'

In [17]:
"Parse the Json data to a dataframe"
fob=open(js, 'r')
fob=fob.read()
json_data=pd.read_json(fob)
json_data.head(2)


firstName   lastName  age  ...     address_city  address_postcode  debt
0     Janet  Whittaker   79  ...  Christopherland           N49 2LB   NaN
1    Kieran      Heath   83  ...       East Mandy           BA1 4GB   NaN

[2 rows x 12 columns]

In [18]:
"Parse the xml data to a dataframe"
fob=open(xml, 'r')
fob=fob.read()
Soup=BeautifulSoup(fob,'html.parser')
users=Soup.findAll('user')

lastname=[]
firstname=[]
address_postcode=[]
age=[]
commute_distance=[]
company=[]
dependants=[]
marital_status=[]
pension=[]
retired=[]
salary=[]
sex=[]

for user in users:
  lastname.append(user.get('lastname'))
  firstname.append(user.get('firstname'))
  address_postcode.append(user.get('address_postcode'))
  age.append(user.get('age'))
  commute_distance.append(user.get('commute_distance'))
  company.append(user.get('company'))
  dependants.append(user.get('dependants'))
  marital_status.append(user.get('marital_status'))
  pension.append(user.get('pension'))
  retired.append(user.get('retired'))
  salary.append(user.get('salary'))
  sex.append(user.get('sex'))

xml_data=pd.DataFrame([firstname,lastname, address_postcode, age, commute_distance,company,dependants, marital_status, \
                 pension, retired, salary,sex]).T
                
xml_data.columns=['firstname','lastname', 'address_postcode', 'age', 'commute_distance','company','dependants',\
            'marital_status', 'pension', 'retired', 'salary','sex']

xml_data.head(2)

firstname lastname address_postcode age  ... pension retired salary     sex
0    Hannah    Jones          N06 4LG  21  ...       0   False  20603  Female
1     Tracy   Rowley           M1 6JD  50  ...       0   False  39509  Female

[2 rows x 12 columns]

In [19]:
"parse CSV data to a dataframe"
csv_data=pd.read_csv(csv)
csv_data.head()

First Name Second Name  ...  Vehicle Year  Vehicle Type
0     Oliver       Brady  ...          2003         Sedan
1      Denis     Jackson  ...          2011   Convertible
2     Joshua    Williams  ...          1999         Sedan
3    Malcolm     Johnson  ...          1996  Sedan, Wagon
4     Ashley       Bates  ...          2018         Sedan

[5 rows x 8 columns]

In [20]:
"Sort the respective data by their Firstname"
json_data=json_data.sort_values('firstName').reset_index().drop('index', axis=1)
csv_data=csv_data.sort_values('First Name').reset_index().drop('index', axis=1)
xml_data=xml_data.sort_values('firstname').reset_index().drop('index', axis=1)

"Create new column Full Name to serve as our Primary ID"
json_data['Full Name']=json_data['firstName']+ ' ' + json_data['lastName']
json_data['Full Name']=json_data['Full Name'].str.upper()
csv_data['Full Name']=csv_data['First Name']+ ' ' + csv_data['Second Name']
csv_data['Full Name']=csv_data['Full Name'].str.upper()
xml_data['Full Name']=xml_data['firstname']+ ' ' + xml_data['lastname']
xml_data['Full Name']=xml_data['Full Name'].str.upper()

In [21]:
"Combine the three dataframes to one using merge function"
xml_csv=xml_data.merge (csv_data, how='outer', on='Full Name')
Data=xml_csv.merge(json_data, how='outer', on='Full Name')

In [22]:
"Drop duplicate columns;FirstName, LastName, address_postcode, age, Sex"
Data=Data.drop(['address_postcode_y', 'age_x', 'age_y', 'sex', 'First Name','Second Name', 'firstName', 'lastName'], axis=1)

In [23]:
Data.head(10)

firstname    lastname  ...       address_city      debt
0     Aaron       Marsh  ...           West Tom       NaN
1     Aaron         Kay  ...        South Allan       NaN
2     Aaron      Thomas  ...         Darrentown       NaN
3     Abbie       Doyle  ...    South Juliefurt       NaN
4     Abbie     Hawkins  ...   East Trevorshire       NaN
5     Abbie     O'Brien  ...     Frederickhaven       NaN
6     Abbie       Ahmed  ...         Tomborough   7543.96
7   Abigail      Barnes  ...  South Sylviamouth       NaN
8   Abigail   Henderson  ...      Robinsonshire       NaN
9   Abigail  Richardson  ...        Butlershire  11566.64

[10 rows x 25 columns]

# **# Utilizing Information from the text file**

In [24]:
text='user_data.txt'
fob=open(text, 'r')
text=fob.read()
print(text)

"Debra Wood phoned up at the weekend. They mentioned that they might have gotten their security code incorrect on their billing information, numbers in the wrong order or something. They think that it's 592"
"Congratulations on the promotion Howard! Keep up the good work. Enjoy the extra £2000 salary, just make sure not to spend it all like last time Hilary. ;) Remember we still work for Hussain-Adams, at least until you win that yacht. See you on Monday"
"Happy Birthday Ms Molly Dobson! We can't believe you're turning 82 today. Make sure to check out our latest offers on Home Appliances, offer ends midnight."
"INTERNAL MEMO (CONFIDENTIAL): Harrison, we've just found a pretty serious error in Mr Miller's file. He shouldn't be on £24515 for his annual pension. This needs rectifying immediately or we're in big trouble! I think it's either £27334 or £25901... just put the higher one in and hope nobody notices."


Reading through the text file, the following infromation was extracted and will be corrected on the unified record:


1.   Debra Wood security code is to be corrected to (592)
2.   Howard Hilary who works for Hussain-Adams new salary increases by 2000 
3.   Ms Molly Dobson is now 82
4.   Mr Miller whose pension was 24515 should be corrected to 27334



In [25]:
"view the data value BEFORE making changes"
print(Data.loc[Data['Full Name']=="DEBRA WOOD", 'credit_card_security_code'])
print(Data.loc[Data['Full Name']=="HILARY HOWARD", 'salary'])
print(Data.loc[Data['Full Name']=="MOLLY DOBSON", 'Age (Years)'])
print(Data.loc[Data['Full Name']=="LEWIS MILLER", 'pension'])

269    952
Name: credit_card_security_code, dtype: int64
415    84396
Name: salary, dtype: object
783    81
Name: Age (Years), dtype: int64
673    24515
Name: pension, dtype: object


In [26]:
"Debra Wood"
Data.loc[Data['Full Name']=="DEBRA WOOD", 'credit_card_security_code']= 592
"Howard Hilary"
Data.loc[Data['Full Name']=="HILARY HOWARD", 'salary']= int(Data.loc[Data['Full Name']=="HILARY HOWARD", 'salary'])+ 2000
"Ms Molly Dobson"
Data.loc[Data['Full Name']=="MOLLY DOBSON", 'Age (Years)']=82
"Mr Miller"
Data.loc[(Data['lastname']=="Miller") &  (Data['pension']=="24515"), 'pension']= '27334'

In [27]:
"view the data value AFTER making changes"
print(Data.loc[Data['Full Name']=="DEBRA WOOD", 'credit_card_security_code'])
print(Data.loc[Data['Full Name']=="HILARY HOWARD", 'salary'])
print(Data.loc[Data['Full Name']=="MOLLY DOBSON", 'Age (Years)'])
print(Data.loc[Data['Full Name']=="LEWIS MILLER", 'pension'])

269    592
Name: credit_card_security_code, dtype: int64
415    86396
Name: salary, dtype: object
783    82
Name: Age (Years), dtype: int64
673    27334
Name: pension, dtype: object


Connecting to Writing the unified Record(Data) to DB

In [ ]:
pip install pony

In [ ]:
pip install pymysql

In [ ]:
from pony.orm import *


In [ ]:
db = Database()

In [ ]:
db.bind(provider='mysql', host='europa.ashley.work', user='student_bh95tw', passwd='iE93F2@8EhM@1zhD&u9M@K', db='student_bh95tw')

In [ ]:
class Dataframe1(db.Entity):
  firstname=Required(str)
  lastname=Required(str)
  address_postcode=Required(str)
  commute_distance=Required(str)
  company=Required(str)
  dependants=Required(str)
  marital_status=Required(str)	
  pension	=Required(str)
  retired	=Required(str)
  salary=Required(str)	
  Full_Name= Required(str)	
  Age	= Required(int)
  Sex=Required(str)
  Vehicle_Make=Required(str)
  Vehicle_Model=Required(str)
  Vehicle_Year=Required(int)	
  Vehicle_Type= Required(str)
  iban=Required(str)
  credit_card_number=Required(str)	
  credit_card_security_code=Required(int)
  credit_card_start_date=Required(str)
  credit_card_end_date=Required(str)	
  address_main=Required(str)
  address_city=Required(str)	
  debt=Required(str)

In [ ]:
db.generate_mapping(create_tables=True)

In [28]:
Data['dependants'].replace('', '0', inplace=True)


In [29]:
New_Data=Data.to_records(index=False).tolist()

In [ ]:
for record in New_Data:
  db.insert("dataframe1", firstname=record[0],lastname=record[1],address_postcode=record[2],commute_distance=record[3],company=record[4],dependants=record[5],\
  marital_status=record[6],	pension	=record[7],retired	=record[8],salary=str(record[9]),	Full_Name= record[10],	Age	=record[11],Sex=record[12],\
  Vehicle_Make=record[13],Vehicle_Model=record[14],Vehicle_Year=record[15],	Vehicle_Type= record[16],iban=record[17],credit_card_number=str(record[18]),\
  credit_card_security_code=record[19],credit_card_start_date=record[20],credit_card_end_date=record[21],	address_main=record[22],
  address_city=record[23],debt=str(record[24]))
  commit()  
    
    
